{{- if and (not .Values.distributed.enabled) (not .Values.workspace.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dry-run.fullname" . }}
  labels: {{- include "dry-run.labels" . | nindent 4 }}
spec:
  accessModes: {{ toYaml .Values.workspace.accessModes | nindent 4 }}
  {{- with .Values.workspace.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.workspace.size }}
{{- end }}
