{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dry-run.fullname" . }}
  labels:
    {{- include "dry-run.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}{{ toYaml . | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels: {{- include "dry-run.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /api/v1/metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      authorization:
        type: Bearer
        credentials:
          name: {{ include "dry-run.secretName" . }}
          key: metricsToken
{{- end }}
