import { appendFileSync, readFileSync } from "node:fs";
import { atomicWritePrivate } from "./storage.ts";
import { compareExperiments, type ExperimentComparison, type ExperimentDocument } from "./experiment.ts";

const COMMENT_MARKER = "<!-- dry-run-quality-report -->";

export interface PrQualityReport {
  markdown: string;
  comparison: ExperimentComparison;
  conclusion: "improved" | "regressed" | "unchanged" | "tradeoff";
  fail: boolean;
}

export function createPrQualityReport(baseline: ExperimentDocument, candidate: ExperimentDocument): PrQualityReport {
  const comparison = compareExperiments(baseline, candidate);
  const positive = comparison.scoreDeltas.filter((score) => score.delta > 1e-9).length + comparison.improvements.length;
  const negative = comparison.scoreDeltas.filter((score) => score.delta < -1e-9).length + comparison.regressions.length;
  const conclusion = negative && positive ? "tradeoff" : negative ? "regressed" : positive ? "improved" : "unchanged";
  const baselineLatency = mean(baseline.results.map((result) => result.durationMs));
  const candidateLatency = mean(candidate.results.map((result) => result.durationMs));
  const baselineCost = baseline.summary.costUsd ?? 0;
  const candidateCost = candidate.summary.costUsd ?? 0;
  const baselineTokens = baseline.summary.tokens ?? 0;
  const candidateTokens = candidate.summary.tokens ?? 0;
  const icon = conclusion === "improved" ? "✅" : conclusion === "regressed" ? "❌" : conclusion === "tradeoff" ? "⚠️" : "➖";
  const lines = [
    COMMENT_MARKER,
    `## ${icon} Dry Run quality report`,
    "",
    `**${safe(candidate.name)}** compared with **${safe(baseline.name)}** · ${conclusion}`,
    "",
    "| Signal | Baseline | Candidate | Delta |",
    "|---|---:|---:|---:|",
    `| Passed cases | ${baseline.summary.passed}/${baseline.summary.total} | ${candidate.summary.passed}/${candidate.summary.total} | ${signed(candidate.summary.passed - baseline.summary.passed)} |`,
    `| Mean latency | ${formatMs(baselineLatency)} | ${formatMs(candidateLatency)} | ${signed(candidateLatency - baselineLatency, "ms")} |`,
    `| Tokens | ${formatNumber(baselineTokens)} | ${formatNumber(candidateTokens)} | ${signed(candidateTokens - baselineTokens)} |`,
    `| Cost | ${formatUsd(baselineCost)} | ${formatUsd(candidateCost)} | ${signed(candidateCost - baselineCost, " USD", 6)} |`,
    "",
  ];
  if (comparison.scoreDeltas.length) {
    lines.push("### Score deltas", "", "| Scorer | Baseline | Candidate | Delta | Pass-rate delta |", "|---|---:|---:|---:|---:|");
    for (const score of comparison.scoreDeltas) lines.push(`| ${safe(score.name)} | ${pct(score.baseline)} | ${pct(score.candidate)} | ${signed(score.delta * 100, " pp")} | ${signed(score.passRateDelta * 100, " pp")} |`);
    lines.push("");
  }
  if (comparison.regressions.length) {
    lines.push(`<details open><summary><strong>${comparison.regressions.length} regression(s)</strong></summary>`, "");
    for (const item of comparison.regressions.slice(0, 50)) lines.push(`- \`${safeCode(item.caseId)}#${item.trial}\` — ${safe(item.reason)}`);
    if (comparison.regressions.length > 50) lines.push(`- …and ${comparison.regressions.length - 50} more`);
    lines.push("", "</details>", "");
  }
  if (comparison.improvements.length) {
    lines.push(`<details><summary><strong>${comparison.improvements.length} improvement(s)</strong></summary>`, "");
    for (const item of comparison.improvements.slice(0, 50)) lines.push(`- \`${safeCode(item.caseId)}#${item.trial}\` — ${safe(item.reason)}`);
    if (comparison.improvements.length > 50) lines.push(`- …and ${comparison.improvements.length - 50} more`);
    lines.push("", "</details>", "");
  }
  if (comparison.added.length || comparison.removed.length) lines.push(`Cases: **${comparison.added.length} added**, **${comparison.removed.length} removed**.`, "");
  lines.push("<sub>Generated by dry-run · deterministic experiment comparison</sub>");
  return { markdown: lines.join("\n").slice(0, 64_000), comparison, conclusion, fail: comparison.regressions.length > 0 || comparison.scoreDeltas.some((score) => score.delta < -1e-9) };
}

export function writePrQualityReport(report: PrQualityReport, opts: { output?: string; summaryFile?: string } = {}): void {
  if (opts.output) atomicWritePrivate(opts.output, `${report.markdown}\n`);
  const summaryFile = opts.summaryFile ?? process.env.GITHUB_STEP_SUMMARY;
  if (summaryFile) appendFileSync(summaryFile, `${report.markdown}\n`, "utf8");
}

export async function postGithubPrComment(markdown: string, opts: { token?: string; repository?: string; pullRequest?: number; apiUrl?: string; fetch?: typeof fetch } = {}): Promise<{ action: "created" | "updated"; id: number; url?: string }> {
  const token = opts.token ?? process.env.GITHUB_TOKEN;
  if (!token) throw new Error("GITHUB_TOKEN is required to post a pull-request comment");
  const repository = opts.repository ?? process.env.GITHUB_REPOSITORY;
  if (!repository || !/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(repository)) throw new Error("GITHUB_REPOSITORY must be owner/name");
  const pullRequest = opts.pullRequest ?? pullRequestFromEvent(process.env.GITHUB_EVENT_PATH);
  if (!Number.isInteger(pullRequest) || pullRequest! < 1) throw new Error("A pull-request number is required");
  const api = new URL(opts.apiUrl ?? process.env.GITHUB_API_URL ?? "https://api.github.com");
  if (api.protocol !== "https:" || api.username || api.password || api.search || api.hash) throw new Error("GitHub API URL must be credential-free HTTPS");
  const request = opts.fetch ?? fetch;
  const base = new URL(`/repos/${repository}/issues/${pullRequest}/comments`, api);
  const headers = { Accept: "application/vnd.github+json", Authorization: `Bearer ${token}`, "Content-Type": "application/json", "X-GitHub-Api-Version": "2022-11-28" };
  const listed = await request(`${base}?per_page=100`, { headers, redirect: "error" });
  if (!listed.ok) throw new Error(`GitHub comments request failed with HTTP ${listed.status}`);
  const comments = await listed.json() as unknown;
  const existing = Array.isArray(comments) ? comments.find((comment) => isRecord(comment) && typeof comment.body === "string" && comment.body.includes(COMMENT_MARKER) && isRecord(comment.user) && comment.user.type === "Bot") : undefined;
  const body = markdown.includes(COMMENT_MARKER) ? markdown : `${COMMENT_MARKER}\n${markdown}`;
  const target = existing && typeof existing.id === "number" ? new URL(`/repos/${repository}/issues/comments/${existing.id}`, api) : base;
  const response = await request(target, { method: existing ? "PATCH" : "POST", headers, redirect: "error", body: JSON.stringify({ body: body.slice(0, 64_000) }) });
  if (!response.ok) throw new Error(`GitHub comment ${existing ? "update" : "create"} failed with HTTP ${response.status}`);
  const result = await response.json() as unknown;
  if (!isRecord(result) || typeof result.id !== "number") throw new Error("GitHub comment response is invalid");
  return { action: existing ? "updated" : "created", id: result.id, ...(typeof result.html_url === "string" ? { url: result.html_url } : {}) };
}

function pullRequestFromEvent(file: string | undefined): number | undefined {
  if (!file) return undefined;
  try {
    const event = JSON.parse(readFileSync(file, "utf8")) as unknown;
    return isRecord(event) && isRecord(event.pull_request) && typeof event.pull_request.number === "number" ? event.pull_request.number : undefined;
  } catch { return undefined; }
}
function safe(value: unknown): string { return String(value ?? "").replace(/\|/g, "\\|").replace(/@/g, "@\u200b").replace(/[\r\n]+/g, " ").slice(0, 500); }
function safeCode(value: unknown): string { return String(value ?? "").replace(/`/g, "'").replace(/[\r\n]+/g, " ").slice(0, 160); }
function signed(value: number, suffix = "", digits = 2): string { const normalized = Math.abs(value) < 10 ** -(digits + 1) ? 0 : value; return `${normalized > 0 ? "+" : ""}${normalized.toFixed(Number.isInteger(value) && !suffix ? 0 : digits)}${suffix}`; }
function formatMs(value: number): string { return `${Math.round(value)}ms`; }
function formatNumber(value: number): string { return new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value); }
function formatUsd(value: number): string { return `$${value.toFixed(6)}`; }
function pct(value: number): string { return `${(value * 100).toFixed(1)}%`; }
function mean(values: number[]): number { return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0; }
function isRecord(value: unknown): value is Record<string, any> { return typeof value === "object" && value !== null && !Array.isArray(value); }
